# Generated by Django 5.0.2 on 2024-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='latest_message',
            field=models.CharField(default='default', max_length=255, verbose_name='Latest Message'),
        ),
    ]
