# Generated by Django 4.2 on 2024-03-12 15:52

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_conversation_latest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latest_message',
            field=django_cryptography.fields.encrypt(models.CharField(default='default', max_length=255, verbose_name='Latest Message')),
        ),
        migrations.AlterField(
            model_name='message',
            name='details',
            field=django_cryptography.fields.encrypt(models.CharField(default='default', max_length=255, verbose_name='Details')),
        ),
    ]
