# Generated by Django 4.2.11 on 2024-03-13 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
