# Generated by Django 4.2.11 on 2024-03-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_conversation_latest_message_and_more'),
        ('mainapp', '0006_alter_userprofile_profile_pic'),
    ]

    operations = [
    ]
