# Generated by Django 4.2.11 on 2024-03-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(max_length=255, null=True, verbose_name='FCM Token'),
        ),
    ]
