# Generated by Django 4.2.11 on 2024-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_remove_userprofile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_counter',
            field=models.IntegerField(default=0),
        ),
    ]
