# Generated by Django 4.2.11 on 2024-03-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_userprofile_notification_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.CharField(default='default', max_length=255, verbose_name='Details'),
        ),
    ]
