# Generated by Django 4.2.11 on 2024-04-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
