# Generated by Django 4.2.11 on 2024-04-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_borrower', to='mainapp.userprofile'),
        ),
    ]
