# Generated by Django 4.2.11 on 2024-05-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
    ]
