name: esrs-group-9
services:
  web:
    build:
      context: ..
      dockerfile: ./Dockerfile
    interfaces:
      main:
        port: 8000
    debug:
      volumes:
        volume:
          host_path: .
          mount_path: /app
    reserved_name: web
