# Generated by Django 5.0.2 on 2024-02-16 15:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(default='default', max_length=255, verbose_name='Book Title')),
                ('book_author', models.CharField(default='default', max_length=255, verbose_name='Book Author')),
                ('genre', models.CharField(default='default', max_length=255, verbose_name='Genre')),
                ('published_date', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Publish Date')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_book_id', models.IntegerField(default=1, verbose_name='Owner Book ID')),
                ('lender_id', models.IntegerField(default=1, verbose_name='Lender ID')),
                ('from_date', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='From Date')),
                ('to_date', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='To Date')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=255, verbose_name='Name')),
                ('username', models.CharField(default='default', max_length=255, unique=True, verbose_name='Username')),
                ('password', models.CharField(default='default', max_length=255, verbose_name='Password')),
                ('email', models.CharField(default='default', max_length=255, verbose_name='Email Address')),
                ('primary_location', models.CharField(default='default', max_length=255, verbose_name='Primary Location')),
                ('current_location', models.CharField(default='default', max_length=255, verbose_name='Current Location')),
                ('review', models.IntegerField(null=True, verbose_name='Review Score')),
            ],
        ),
        migrations.CreateModel(
            name='userBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_book_id', models.IntegerField(default=1, verbose_name='Owner Book ID')),
                ('availability', models.BooleanField(default=True, verbose_name='Available')),
                ('booked', models.CharField(default='default', max_length=255, verbose_name='Booked')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_id', to='mainapp.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_id', to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(default='default', max_length=255, verbose_name='From User')),
                ('to_user', models.CharField(default='default', max_length=255, verbose_name='To User')),
                ('details', models.CharField(default='default', max_length=255, verbose_name='Details')),
                ('request_type', models.IntegerField(default=1, verbose_name='Request Type')),
                ('request_value', models.CharField(default='default', max_length=255, verbose_name='Request Value')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0), verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0), verbose_name='Modified On')),
                ('notification_status', models.IntegerField(default=1, verbose_name='Notification Status')),
                ('user_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_id', to='mainapp.userbooks')),
            ],
        ),
    ]
