# Generated by Django 5.0.2 on 2024-02-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='user_book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to='mainapp.userbooks'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mainapp.book'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='mainapp.user'),
        ),
    ]
