# Generated by Django 4.2.6 on 2024-03-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='returned_on',
            field=models.DateField(default=None, verbose_name='Returned On'),
        ),
    ]
