# Generated by Django 5.0.2 on 2024-02-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='username_1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='username_2',
        ),
    ]
