# Generated by Django 4.2.6 on 2024-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='returned_on',
            field=models.DateField(null=True, verbose_name='Returned On'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='review',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Review Score'),
        ),
    ]
