# Generated by Django 4.2.10 on 2024-02-19 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='default', max_length=255, verbose_name='Book Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_title',
            field=models.CharField(default='default', max_length=255, verbose_name='Book Title'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='default', max_length=255, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Publish Date'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_location', models.CharField(default='default', max_length=255, verbose_name='Primary Location')),
                ('current_location', models.CharField(default='default', max_length=255, verbose_name='Current Location')),
                ('phone_number', models.CharField(default='default', max_length=255, verbose_name='Phone Number')),
                ('birth_date', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Birth Date')),
                ('review', models.IntegerField(null=True, verbose_name='Review Score')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True, verbose_name='Available')),
                ('booked', models.CharField(default='default', max_length=255, verbose_name='Booked')),
                ('book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_books_book', to='mainapp.book')),
                ('currently_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_with', to='mainapp.userprofile')),
                ('owner_book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mainapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(default='default', max_length=255, verbose_name='Details')),
                ('request_type', models.IntegerField(default=1, verbose_name='Request Type')),
                ('request_value', models.CharField(default='default', max_length=255, verbose_name='Request Value')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0), verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0), verbose_name='Modified On')),
                ('notification_status', models.IntegerField(default=1, verbose_name='Notification Status')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('user_book_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_user_book', to='mainapp.userbooks')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='From Date')),
                ('to_date', models.DateField(default=datetime.date(2024, 1, 1), verbose_name='To Date')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('borrower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_borrower', to='mainapp.userprofile')),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_owner', to='mainapp.userprofile')),
            ],
        ),
    ]
