# Generated by Django 5.0.2 on 2024-02-16 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_userbooks_currently_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='currently_with',
            field=models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mainapp.userprofile'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_with', to='mainapp.userprofile'),
        ),
    ]
