# Generated by Django 5.0.2 on 2024-02-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_userbooks_user_id_alter_messages_to_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbooks',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_borrower', to='mainapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_owner', to='mainapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='owner_book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mainapp.userprofile'),
        ),
    ]
