# Generated by Django 5.0.2 on 2024-02-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_messages_user_book_id_alter_userbooks_book_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lender_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='owner_book_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_borrower', to='mainapp.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_owner', to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_user_book', to='mainapp.userbooks'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_books_book', to='mainapp.book'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='owner_book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mainapp.user'),
        ),
        migrations.AlterField(
            model_name='userbooks',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_books_user', to='mainapp.user'),
        ),
    ]
