# Generated by Django 4.2.11 on 2024-03-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
