# Generated by Django 4.2.6 on 2024-02-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_book_author_remove_book_isbn_and_more'),
        ('mainapp', '0004_alter_message_from_user_alter_message_to_user'),
    ]

    operations = [
    ]
