# Generated by Django 4.2.6 on 2024-03-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_conversation_latest_message_and_more'),
        ('mainapp', '0005_remove_userprofile_profile_picture'),
    ]

    operations = [
    ]
