# Generated by Django 4.2.11 on 2024-03-15 14:57

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=django_cryptography.fields.encrypt(models.ImageField(blank=True, upload_to='images')),
        ),
    ]
