# Generated by Django 4.2.11 on 2024-03-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_booking_user_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='message',
            name='notification_status',
        ),
    ]
