# Generated by Django 4.2.11 on 2024-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_message_modified_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.IntegerField(default=1, verbose_name='Notify Type')),
                ('notify_value', models.CharField(default='default', max_length=255, verbose_name='Notify Value')),
            ],
        ),
    ]
