# Generated by Django 4.2.11 on 2024-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_transactions_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='booked',
            field=models.CharField(default='No', max_length=255, verbose_name='Booked'),
        ),
    ]
