# Generated by Django 4.2.11 on 2024-05-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to='mainapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mainapp.notification'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mainapp.userprofile'),
        ),
    ]
