name: Architect Production Deployment

on:
  release:
    types:
      - published

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_PRODUCTION: true
  COMPONENT_FILE_PATH: architect.yml
  ARCHITECT_ACCOUNT: thepercyj
  COMPONENT_NAME: esrs-group-9
  ENVIRONMENT_NAME: example-environment

jobs:
  architect_create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: crazy-max/ghaction-github-runtime@v2 # Exports internal envs for Github Actions. Required for register caching to work.
      - name: Install Architect CLI
        run: npm install -g @architect-io/cli
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }} # These secrets were created on your behalf
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t latest
      - name: Deploy component
        run: architect deploy --auto-approve -e ${{ env.ENVIRONMENT_NAME }} ${{ env.COMPONENT_NAME }}:latest
